import { JetBrains_Mono as JetBrainsMono } from "next/font/google";
import "./globals.css";
import { Weight } from "lucide-react";

const jetBrainsMono = JetBrainsMono({
  variable: "--font-jetbrains-mono",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={jetBrainsMono.variable}>{children}</body>
    </html>
  );
}
